### PR TITLE
fix(ENTESB-13221): Update template to be more generic

### PR DESCRIPTION
**Pull request by phantomjinx**
* Fix omissions and errors as well as adding more parameters for
  controlling inputs

### CODE REVIEW

**Comment by phantomjinx** [comment]
Goes in hand with https://github.com/syndesisio/syndesis/pull/8129

**Comment by phantomjinx** [comment]
Generated [template](https://gist.github.com/phantomjinx/797de72e6f4386809ae1349e85c19c95)

**Comment by heiko-braun** [comment]
looks good. I leave my comments on syndesisio/syndesis#8129. For 1.9 I would carry on witht he template that's present and introduce this change for 1.10

**Comment by heiko-braun** [comment]
@phantomjinx Let's retarget this for `master`, so it will be included with 1.10

**Comment by phantomjinx** [comment]
Moved to master -> #236

**Pull request closed without merging**
