### PR TITLE
Fixes syndesisio/syndesis#5010: Use oauth proxy 4.1

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by heiko-braun** [comment]
@nicolaferraro done

**Comment by avano** [comment]
@heiko-braun just fyi: 

```
docker pull registry.access.redhat.com/openshift4/ose-oauth-proxy:4.1
Error response from daemon: unsupported: This repo requires terms acceptance and is only available on registry.redhat.io
```

**Comment by nicolaferraro** [comment]
So it must be pulled from the new registry, right @avano ?

**Comment by heiko-braun** [comment]
@nicolaferraro yes, I think so

**Comment by heiko-braun** [comment]
@nicolaferraro This might not work ootb with the current means to authenticate (service account linkage). Can I handover to you at this point?

**Comment by avano** [comment]
correct:

```
$ docker login registry.redhat.io                                   
Username: avano@redhat.com
Password: 
WARNING! Your password will be stored unencrypted in /home/avano/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
$ docker pull registry.redhat.io/openshift4/ose-oauth-proxy:4.1
4.1: Pulling from openshift4/ose-oauth-proxy
18f0f6de4601: Pull complete 
db1d55616933: Pull complete 
25d3230a0c3e: Pull complete 
162f5cc216c5: Pull complete 
Digest: sha256:cda9f48b615458952a665209126ec8c60d1b293c4a03ff7d96d113fac1a8268c
Status: Downloaded newer image for registry.redhat.io/openshift4/ose-oauth-proxy:4.1

```

**Comment by heiko-braun** [comment]
In the final resources (i.e. [1] taken from 1.6.x latest) the references are updated to registry.redhat.io.

[1] https://github.com/syndesisio/fuse-online-install/blob/1.6.23/resources/fuse-online-image-streams.yml#L69

**Pull request merged**
