### PR TITLE
Install secret for any 1.6.x release version

### PR DESCRIPTION
**Pull request by lgarciaaco**
Fixes https://github.com/syndesisio/fuse-online-install/issues/96

### CODE REVIEW

**Comment by heiko-braun** [comment]
@avano Mind a review?

**Comment by avano** [comment]
@lgarciaaco 

```
bash update_ocp.sh
pull secret 'syndesis-pull-secret' is missing, creating ...
enter username for registry.redhat.io and press [ENTER]: 
enter password for registry.redhat.io and press [ENTER]: 
update_ocp.sh: line 447: local: can only be used in a function
```

removing the `local` from line 447 seemed to work.

btw don't forget to backport to 1.6.x as well

**Comment by avano** [comment]
looks ok now

**Comment by lgarciaaco** [comment]
@avano can you +1 so it gets merged?

**Comment by avano** [comment]
@lgarciaaco I couldn't :-) seems I don't have any permissions here

**Comment by heiko-braun** [comment]
@avano I've granted you write access

**Comment by lgarciaaco** [comment]
@heiko-braun what about me?? :)

**Comment by heiko-braun** [comment]
Your time will come young Jedi ...

**Comment by heiko-braun** [comment]
@lgarciaaco You already have write access, but we prevent people from merging their own code

**Pull request merged**
