### PR TITLE
Added CPU limits and requests to pods

### PR DESCRIPTION
**Pull request by honghuac**
CPU requests help to stablise the startup of pods, with assurance of minimum CPU allocation. I have added them to the deployment configurations of the pods, and also at container level where needed.

### CODE REVIEW

**Comment by zregvart** [comment]
@rhuss / @syndesisio/backend any thoughts? Looks good to me.

**Comment by KurtStam** [comment]
Looks good to me, why wouldn't we do this on the project too? 
Also I think the `syndesis-server` might need more CPU resources?

**Comment by heiko-braun** [comment]
I think this file is not used anymore, @rhuss can you tell us where these are would be applicable? Some where in Syndesis I guess ...

**Comment by rhuss** [comment]
Thanks for the PR, some comments:

* This file is generated, so in order to change this it should be done upstream in `syndesis/install/generator`
* Actually I love to have limit and request the same number to be in the "Guaranteed" QoS class. However, most clusters I've seen so far have a fixed ration between limit and request so that typical limit is ignored and e.g. taken twice as large as the request spec. This puts all pods into the "Burstable" QoS class (not so bad either). For syndesis-server we should fix it to use the same parameter for request and limits.
* I have no strong opinions on cpu resources as this is a compressible resource (so no hard limit, you just get less if there is a CPU resource pressure). How much CPU do we actually use ? Are we CPU bound ? (doubt that). Since we are still single tenant I don't expect much load on our infrastructure pods. This might be diffeferent for the runtime pods, but making a general prediction for those is impossible as it really depends on the integration created. I think we should make those variables part of the Integration definition an query for them from the UI (with some defaults).

**Comment by heiko-braun** [comment]
@honghuac We would need this changes in syndesisio/syndesis. See Rolands comments in https://github.com/syndesisio/fuse-online-install/pull/65#issuecomment-446176874

> This file is generated, so in order to change this it should be done upstream in `syndesis/install/generator`

**Comment by heiko-braun** [comment]
Closing due to inactivity

**Pull request closed without merging**
