### PR TITLE
Backport changes to 1.6.x

### PR DESCRIPTION
**Pull request by lgarciaaco**

### CODE REVIEW

**Comment by lgarciaaco** [comment]
Fixes https://github.com/syndesisio/syndesis/issues/4945

**Comment by lgarciaaco** [comment]
@avano pls review

**Comment by avano** [comment]
@lgarciaaco please revert the image changes in `fuse_online_config.sh` `resources/fuse-online-image-streams.yml` `resources/fuse-online-operator.yml`

**Comment by lgarciaaco** [comment]
Fixes https://github.com/syndesisio/syndesis/issues/4965

**Pull request merged**
