### PR TITLE
Remove Camel-K resource when installing from template

### PR DESCRIPTION
**Pull request by lgarciaaco**

### CODE REVIEW

**Comment by lgarciaaco** [comment]
Fixes https://github.com/syndesisio/syndesis/issues/5194

**Comment by nicolaferraro** [comment]
Same strategy I was attempting.. but..
If you run `bash release.sh --dry-run` you see that the template is overridden because it comes from the syndesis image.

In order for this to work you need: https://github.com/syndesisio/syndesis/pull/5199 (that adds some markers).

**Comment by lgarciaaco** [comment]
This is madness ... too much cross reference

**Comment by heiko-braun** [comment]
@lgarciaaco Can you uupdate the PR to with start / end markers? https://github.com/syndesisio/syndesis/pull/5199/files#diff-2a8da49fc067aa8645cce39c6c1e5dffR1898

We will bring this to 1.6.x

**Comment by lgarciaaco** [comment]
@nicolaferraro ^^

**Comment by heiko-braun** [comment]
thanks @lgarciaaco !

**Pull request merged**
