### PR TITLE
ENTESB-11667: Full refactor of install scripts to use CLI tools

### PR DESCRIPTION
**Pull request by nicolaferraro**
Fixes ENTESB-11667

I've thrown away most of the 1.7 scripts and simplified the process for 1.8. Now the scripts download the syndesis and kamel CLI to execute stuff. User commands are the same as before.

I've:
- centralized configuration in a single common_config.sh file (configuration is now minimal)
- updated install_ocp.sh
- updated update_ocp.sh (naively override the operators, to trigger upgrade)
- updated release.sh (commits settings and tags, no more resource generation)
- moved useful stuff (e.g. image downloader) to `/utils`

Things remaining to do later:
- Find a download location for kamel and syndesis CLI
- Allow QE to hack on the release (e.g. I've not found a easy way to just change registry.redhat.io to brew in syndesis...)

### CODE REVIEW

**Comment by heiko-braun** [comment]
@oscerd Please allow these PR to be reviewed before simply approving them.

**Comment by oscerd** [comment]
I don't "simply approve" the PR. I reviewed it and it looks good from my pov. I won't approve anything else on this project.

**Comment by oscerd** [comment]
and I think it's a bit offensive to say I simply approve something.

**Comment by heiko-braun** [comment]
Sorry, I didn't mean to be offensive, but I still believe you are too quick approving this. There was an explicit review requested, and I think we should wait for the feedback or at least check with the requested reviewers if a PR is good to go.

**Comment by oscerd** [comment]
You can always allow only a subset of organization members to be able to approve here or in Syndesis, so you won't have this kind of problem anymore.

**Comment by janstey** [comment]
Not sure we want to lock down who can approve/review PRs. Reviewing is time consuming business and if someone from the wider Fuse team wants to chip in, I think that is great :-)

**Pull request merged**
