### PR TITLE
Recreate operator resources to include missing envs and roles

### PR DESCRIPTION
**Pull request by lgarciaaco**
Fixes https://github.com/syndesisio/fuse-online-install/issues/98

### CODE REVIEW

**Comment by avano** [comment]
@lgarciaaco there is also a missing image stream for postgres exporter

@heiko-braun do we "support" user changes in syndesis resources (deploymentconfigs, etc.)? If so, then deleting and re-creating will destroy user changes :/

**Comment by lgarciaaco** [comment]
What would be the best way to create that single Image Stream? I can think of:

 - Do some magic and try to regex out the Image Stream definition from `resources/fuse-online-image-streams.yml`. I don't like this, if someone changes later on the start or end of my regex, it will break.
- Create a separate file and duplicate the definition of the IS. I don't like this because we have duplicated code, yet I like it more than the first option.
- Follow the same approach as with `resources/fuse-online-operator.yml`, delete and create all Image Streams. I like this one the most, but not sure about the implications. We actually don't have to delete the image streams, we can just recreate them, the existing ones will fail and only `postgres_exporter` will be created.

@heiko-braun @avano @rhuss

**Comment by avano** [comment]
btw rethinking the question about user changes.. the upgrade itself is replacing the old resources, so scratch my question :-)

**Comment by lgarciaaco** [comment]
I did an upsy and merged to master ...

**Comment by avano** [comment]
@lgarciaaco 

> We actually don't have to delete the image streams, we can just recreate them, the existing ones will fail and only postgres_exporter will be created

+1

**Comment by avano** [comment]
@lgarciaaco I tried it and works OK

**Comment by heiko-braun** [comment]
@lgarciaaco don't forget to be bring these changes on 1.6.x, if applicable. The bot can help with it.

**Pull request merged**
